# Get length and width of a rectangle using prompt. Calculate its area (area = length x width) and perimeter (perimeter = 2 x (length + width))
print('====== RECTANGLE =======')
length = input('Enter length: ')
width = input('Enter width: ')
print('The area of the rectangle is ', float(length) * float(width))
print('The perimeter of the rectangle is ', float(length) + float(width))